users:
    joshua: ENC[AES256_GCM,data:lwvAepBgR7kFJDhcRHOyNy/KdwXX1xQiA7jnxxOkYwfylELGr9SuTwqDraAyt+seesAbj1PAN7Ncr89Lg3qVdZelvwcFlHklvQ==,iv:g36cfRZcv8710lrwI4cy0GPQ9fndhgEZn75uk06xF+M=,tag:GduYdkT8IFjIo3VJ5oA7pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1de6wyynhrf0mjxg85dq8layuwqudj527pfv9l4v6sdcu8a5w0ggqedl40j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEb1RjbmFkSVJWSWlxYlV5
            bW1nK1FnbUFlOGMxL1pIQlZyank4YndHY2pJCkR4M0lPUXVPVm95NnJidUwzc1pY
            ZURiaTAzRjJkY2tEYTJpcnlkZUZuK0EKLS0tIEdxMkNvSjJKZTFURTBTRXN3eDk4
            WXZwVGRCaGswWEpRM0Z0RHVwMmZrdmsKp5x/DWHTAht8DmcjOyN1DHXX7OvC7peA
            D0VkmmhL6rIqadY6HvIBku/FwMner+j0U8yy3zlad4Qhs2rWd/Qu+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-23T00:18:44Z"
    mac: ENC[AES256_GCM,data:klUkcrYuTcr49MBN4cjsTmJDMDKgnu8/H+bbaQglVaFRrlUxxbbV+JXy0H0gFzCMEVKvek3YYSyRh483deD+P8iNPGYeTKJ4MHPWiWhQrkDx4EQ+DtROGfuVYrn1YnTXSZmyUb7/MZkZuf98W8bN7dL2WXtSDlppI+3Ap5UEV1c=,iv:OOJ/I0YysqkNijD3CMugi1+CtUOhXjwohh/lMpsGng8=,tag:u2z1C8Rkzl+KjDbc59EVlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
